      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          
          # Build proses
          ./gradlew make makePluginsJson
          ./gradlew ensureJarCompatibility
          
          # Validasi build
          if [ ! -f "build/plugins.json" ]; then
            echo "ERROR: Gagal build!"
            exit 1
          fi

          # 4. Copy hasil build ke folder "builds"
          # Aktifkan globstar agar tanda ** berfungsi dengan baik
          shopt -s globstar
          
          # Tambahkan '|| true' dan '2>/dev/null' agar proses tetap aman walau file tidak ditemukan
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds/ 2>/dev/null || true
          cp **/build/*.jar $GITHUB_WORKSPACE/builds/ 2>/dev/null || true
          cp build/plugins.json $GITHUB_WORKSPACE/builds/ 2>/dev/null || true
